### PR TITLE
fix(Text): remove default text-align value

### LINKED ISSUE #785: Heading, Text components don't inherit center alignment
Reproduction: https://codesandbox.io/s/center-align-not-working-blade-l1sqi3?file=/src/App.tsx

I added the components inside center aligned div. It gets applied to some component but doesn't work on some components 🤔 

image

### PR DESCRIPTION
**Pull request by saurabhdaware**
Resolves #785 

Change: https://github.com/razorpay/blade/pull/823#discussion_r1015013494

Rest are snapshot updates

### CODE REVIEW

File: packages/blade/src/components/Typography/BaseText/getBaseTextStyles.ts [hunk 1]
```diff
@@ -10,7 +10,7 @@ const getBaseTextStyles = ({
   fontStyle = 'normal',
   textDecorationLine = 'none',
   lineHeight = 'l',
-  textAlign = 'left',
+  textAlign,
```
Comment (saurabhdaware) [inline packages/blade/src/components/Typography/BaseText/getBaseTextStyles.ts:13]: This is the only change. Rest are snapshot updates

**Review by kamleshchandnani — APPROVED** [review]
LGTM 🚢
