### PR TITLE
fix: make Badge and Counter display inline-flex

### LINKED ISSUE #1241: Make `Badge` and `Counter` display inline-block
I think we should make Badge display inline-block by default since it is not taking the full width.

And Link followed by Text can be implemented this way right now-
```
<Text>Some Text <Link>Link</Link></Text>
```

_Originally posted by @saurabhdaware in https://github.com/razorpay/blade/issues/1214#issuecomment-1568268614_

If it has to be `flex`, we can probably make it `inline-flex`

### PR DESCRIPTION
**Pull request by archie252000**
Resolves #1241

### CODE REVIEW

File: packages/blade/src/components/Badge/Badge.tsx [hunk 1]
```diff
@@ -134,7 +134,7 @@ const _Badge = ({
         paddingLeft={horizontalPadding[size]}
         paddingTop={verticalPadding[size]}
         paddingBottom={verticalPadding[size]}
-        display="flex"
+        display="inline-flex"
```
Comment (saurabhdaware) [inline packages/blade/src/components/Badge/Badge.tsx:137]: `inline-flex` is not supported on react native. We'll have to add `isReactNative() ? 'flex' : 'inline-flex'` check here

**Comment by saurabhdaware** [comment]
Thanks for the PR!! Added one comment.

**Comment by anuraghazra** [comment]
Let's update the snapshots?

**Review by divyanshu013 — COMMENTED** [review]
Please also add some relevant screenshots in PR description (also please validate for React Native)

**Comment by archie252000** [comment]
using inline-flex is generating type errors

**Comment by archie252000** [comment]
Noticed one thing ```isReactNative() ? 'flex': 'inline-flex'``` only seems to work only in Storybook story files. In components, it gives the aforementioned type error (error TS2769: No overload matches this call) on the npm pack.

File: packages/blade/src/components/Badge/Badge.tsx [hunk 2]
```diff
@@ -134,7 +134,7 @@ const _Badge = ({
         paddingLeft={horizontalPadding[size]}
         paddingTop={verticalPadding[size]}
         paddingBottom={verticalPadding[size]}
-        display="flex"
+        display={isReactNative() ? "flex" : "inline-flex"}
```
Comment (anuraghazra) [inline packages/blade/src/components/Badge/Badge.tsx:137]:
```suggestion
        display={(isReactNative() ? "flex" : "inline-flex") as never}
```

This should fix the TS error. you can double check by running `yarn tsc:blade`

Comment (saurabhdaware) [reply packages/blade/src/components/Badge/Badge.tsx:137]: Oh yes this is the weird error we randomly face sometimes because of faulty ts plugin. Let me take a pull and fix it.

Comment (saurabhdaware) [reply packages/blade/src/components/Badge/Badge.tsx:137]: @archie252000 You can check and merge this PR into your branch - https://github.com/archie252000/blade/pull/1

I have fixed the build issue and updated the snapshot tests so checks should work fine with this.

Comment (archie252000) [reply packages/blade/src/components/Badge/Badge.tsx]: Yeah, it works. Build errors are gone. Thanks!

**Review by saurabhdaware — DISMISSED** [review]
Thank you so much for contributing this @archie252000 !! Super helpful bug fix. This will be released in next version we release

**Review by saurabhdaware — APPROVED** [review]

**Review by saurabhdaware — APPROVED** [review]

**Comment by archie252000** [comment]
> Thank you so much for contributing this @archie252000 !! Super helpful bug fix. This will be released in next version we release

The pleasure is all mine!
