### PR TITLE
fix(dropdown): dropdown overlay positioning

### LINKED ISSUE #1245: Adjust DropdownOverlay position based on screensize and scroll position
If user is scrolled till bottom, DropdownOverlay should open on top. If trigger is on extreme right, overlay should open a bit towards left.

Similar usecase was mentioned in #1207. We partially solved that issue by giving minWidth and maxWidth but we still need to move overlay according to trigger position

### PR DESCRIPTION
**Pull request by Jaynil1611**
Fixes #1245

### CODE REVIEW

File: packages/blade/src/components/Dropdown/dropdownUtils.ts [hunk 1]
```diff
@@ -324,3 +325,58 @@ export const makeInputDisplayValue = (selectedIndices: number[], options: Option
...
+  bottom?: SpacingValueType;
+  left?: SpacingValueType;
+  right?: SpacingValueType;
+}
+
+export const POSITION_THRESHOLDS = {
+  top: -400,
+  bottom: -400,
+  left: -400,
+  right: -400,
```
Comment (saurabhdaware) [inline packages/blade/src/components/Dropdown/dropdownUtils.ts:347]: Where do these values come from?

**Review by saurabhdaware — COMMENTED** [review]
Thanks for this contribution! This is huge for us. 

Added tiny comments below. Tried it out locally and it works great!

Can you revert the story changes and add a new story for this? In Select and in Menu trigger?


Also do take a pull of this branch once. I fixed that ts error.

File: packages/blade/src/components/Dropdown/dropdownUtils.ts (hunk 1 above)
Comment (Jaynil1611) [reply packages/blade/src/components/Dropdown/dropdownUtils.ts:347]: Since you have kept `max-width` for dropdown overlay as `400px`. I am reusing the same number to calculate height, width available in all positions

File: packages/blade/src/components/Dropdown/docs/stories.ts [hunk 2]
```diff
@@ -604,6 +604,46 @@ const WithControlledMultiSelectStory = `
   export default App;
 `;
 
+const WithBottomAlignedSelectStory = `
```
Comment (anuraghazra) [inline packages/blade/src/components/Dropdown/docs/stories.ts:607]: The Bottom aligned dropdown overlay suppose to go upwards? 

image

File: packages/blade/src/components/Dropdown/DropdownOverlay.web.tsx [hunk 3]
```diff
@@ -60,13 +63,39 @@ type DropdownOverlayProps = {
...
-  const { isOpen, triggererRef, hasLabelOnLeft, dropdownTriggerer } = useDropdown();
+  const { isOpen, triggererRef, hasLabelOnLeft, dropdownTriggerer, setIsOpen } = useDropdown();
   const { theme } = useTheme();
   const [display, setDisplay] = React.useState<'none' | 'block'>('none');
   const [width, setWidth] = React.useState<SpacingValueType>('100%');
+  const [dropdownPosition, setDropdownPosition] = useState<DropdownPosition>({});
 
   const isMenu = dropdownTriggerer !== 'SelectInput';
 
+  const detectOverflowMiddleware = {
```
[the remark this answers is not in the document]
Comment (anuraghazra) [reply packages/blade/src/components/Dropdown/DropdownOverlay.web.tsx:74]: If it is needed can you show an example for me to visualise what edge case is this handling?

File: packages/blade/src/components/Dropdown/docs/stories.ts (hunk 2 above)
Comment (Jaynil1611) [reply packages/blade/src/components/Dropdown/docs/stories.ts:607]: Yes, the playground on local won't work. Check this deployed chromatic [link](https://61c19ee8d3d282003ac1d81c-gwxawxwngs.chromatic.com/?path=/story/components-dropdown-with-select--with-bottom-aligned-select&globals=showInternalComponents:true;measureEnabled:false)

File: packages/blade/src/components/Dropdown/dropdownUtils.ts [hunk 4]
```diff
@@ -324,3 +325,58 @@ export const makeInputDisplayValue = (selectedIndices: number[], options: Option
   // When more than one item is selected, we display the count of items
   return `${selectedIndices.length} items selected`;
 };
+
+interface PositionProp {
```
Comment (anuraghazra) [inline packages/blade/src/components/Dropdown/dropdownUtils.ts:329]: Let's use `type` if possible, interfaces can accidentally be augmented.

File: packages/blade/src/components/Dropdown/DropdownOverlay.web.tsx (hunk 3 above)
[the remark this answers is not in the document]
Comment (Jaynil1611) [reply packages/blade/src/components/Dropdown/DropdownOverlay.web.tsx:74]: We did try out with `flip, autoPlacement, shift` provided out of the box by floating UI, but it didn't work as expected as it used `transform` property which didn't fit the use case here.

[the remark this answers is not in the document]
Comment (Jaynil1611) [reply packages/blade/src/components/Dropdown/DropdownOverlay.web.tsx:74]: You can see with this [story](https://61c19ee8d3d282003ac1d81c-gwxawxwngs.chromatic.com/?path=/story/components-dropdown-with-button-and-link--with-right-aligned-menu&globals=showInternalComponents:true;measureEnabled:false) & change position of the menu button to the edges to see it in action.

File: packages/blade/package.json [hunk 5]
```diff
@@ -283,14 +283,14 @@
...
-      "limit": "17.5 kb",
+      "limit": "19.5 kb",
       "running": false
     },
     {
       "name": "Import Text only",
       "path": "./build/components/index.web.js",
       "import": "{ Text }",
-      "limit": "13 kb",
+      "limit": "14.5 kb",
```
Comment (Jaynil1611) [inline packages/blade/package.json:293]: @anuraghazra I have increased limits here since the validate tree shaking job was failing. [CI](https://github.com/razorpay/blade/actions/runs/5313644080/jobs/9636524037)

File: packages/blade/src/components/Dropdown/DropdownOverlay.web.tsx (hunk 3 above)
[the remark this answers is not in the document]
Comment (anuraghazra) [reply packages/blade/src/components/Dropdown/DropdownOverlay.web.tsx:74]: > We did try out with flip, autoPlacement, shift provided out of the box by floating UI

That's weird, okay we can refactor this later if needed

File: packages/blade/package.json (hunk 5 above)
Comment (anuraghazra) [reply packages/blade/package.json:293]: Sounds good.

File: packages/blade/src/components/Dropdown/dropdownUtils.ts (hunk 1 above)
Comment (anuraghazra) [reply packages/blade/src/components/Dropdown/dropdownUtils.ts:347]: Let's add a comment here.

File: packages/blade/src/components/Dropdown/dropdownUtils.ts [hunk 6]
```diff
@@ -324,3 +325,58 @@ export const makeInputDisplayValue = (selectedIndices: number[], options: Option
...
+};
+
+export const POSITION_THRESHOLDS = {
+  top: -400,
+  bottom: -400,
+  left: -400,
+  right: -400,
+};
+
+export const getDropdownOverlayPosition = ({
```
Comment (anuraghazra) [inline packages/blade/src/components/Dropdown/dropdownUtils.ts:350]: Can we add few comments here? What this is doing?

File: packages/blade/src/components/Dropdown/dropdownUtils.ts [hunk 7]
```diff
@@ -324,3 +325,58 @@ export const makeInputDisplayValue = (selectedIndices: number[], options: Option
...
+  triggererEl: HTMLButtonElement | null;
+}): DropdownPosition => {
+  const zeroSpacing: SpacingValueType = 'spacing.0';
+  const { bottom, right } = position;
+
+  const newPosition: DropdownPosition = { left: zeroSpacing };
+
+  if (!isMenu) {
+    if (bottom > POSITION_THRESHOLDS.bottom) {
+      newPosition.bottom = `${Number(triggererEl?.clientHeight) + 32}px`;
```
Comment (anuraghazra) [inline packages/blade/src/components/Dropdown/dropdownUtils.ts:366]: Where is this 32px coming from?

Comment (anuraghazra) [reply packages/blade/src/components/Dropdown/dropdownUtils.ts:366]: Let's extract to a variable or get this from the `size[32]` tokens

```
import { size } from '~tokens/global';
```

File: packages/blade/src/components/Dropdown/DropdownOverlay.web.tsx (hunk 3 above)
Comment (anuraghazra) [inline packages/blade/src/components/Dropdown/DropdownOverlay.web.tsx:74]: Possible to put this middle ware outside of the function so it doesn't gets recreated everytime? 

Maybe for the `setDropdownPosition` you can pass it via arguments

**Review by anuraghazra — APPROVED** [review]
LGTM, few comments added

**Review by anuraghazra — APPROVED** [review]
