### PR TITLE
fix(BaseInput): Large label alignment

### LINKED ISSUE #1104: TextInput has misalignments when the label overflows to the next line
A couple of label alignment issues that could be addressed:
* When the label overflows it looks weird, maybe we could use `break-word` instead of `break-all` for the `word-break`. Also, the “*” is misaligned.
* During the label overflow I have noticed the border below the TextInput also gets misaligned a little. Not a huge issue but when placed across a form group with multiple inputs it looks strange. [Ref thread](https://razorpay.slack.com/archives/C01H13RTF8V/p1678167510531169).

Screenshot 2023-04-04 at 11 50 03 AM

Screenshot 2023-03-07 at 11 06 11 AM

### PR DESCRIPTION
**Pull request by harshsinghatz**
Resolves #1104 

Fixes:
1. Fixed word break for input text label
2. Position Border Animation relative to Input
3. Add story for large label text

After: 
image
Before: 
image

### CODE REVIEW

**Comment by harshsinghatz** [comment]
@divyanshu013

File: packages/blade/src/components/Input/BaseInput/BaseInputWrapper.tsx [hunk 1]
```diff
@@ -60,23 +60,21 @@ export const BaseInputWrapper = ({
...
+      validationState={validationState}
+      currentInteraction={currentInteraction}
+      position="relative"
+      {...props}
+    >
+      {children}
       <BaseInputAnimatedBorder
         currentInteraction={currentInteraction}
         validationState={validationState}
-        isLabelLeftPositioned={isLabelLeftPositioned}
```
Comment (saurabhdaware) [inline packages/blade/src/components/Input/BaseInput/BaseInputWrapper.tsx:78]: intended to remove this?

File: packages/blade/src/components/Form/FormLabel.tsx [hunk 2]
```diff
@@ -136,7 +136,6 @@ const FormLabel = ({
         width,
         flexShrink: 0,
         marginRight: makeSpace(theme.spacing[5]),
-        wordBreak: 'break-all',
```
Comment (saurabhdaware) [inline packages/blade/src/components/Form/FormLabel.tsx:139]: This might be needed no? It is there to break the single word as well.

we have usecases where label might be single word `temporary_house_address` kind of label. That is breaking after the change -

Before the change
image

After the change
image

File: packages/blade/src/components/Input/TextInput/TextInput.stories.tsx [hunk 3]
```diff
@@ -410,6 +410,17 @@ const TextInputKitchenSinkTemplate: ComponentStory<typeof TextInputComponent> =
           validationState="none"
           helpText="Write your message"
         />
+
+        <TextInput
```
Comment (saurabhdaware) [inline packages/blade/src/components/Input/TextInput/TextInput.stories.tsx:414]: Nice!!

**Review by saurabhdaware — COMMENTED** [review]
Heya! Thanks for the PR 🎉 Overall looks good to me. Added minor comments -

**Comment by divyanshu013** [comment]
@harshsinghatz some comments above, can take another look post that.

File: packages/blade/src/components/Form/FormLabel.tsx (hunk 2 above)
Comment (harshsinghatz) [reply packages/blade/src/components/Form/FormLabel.tsx]: I reverted this, but I was thinking of adding a hyphen for word breaks but it doesn't  seem to work

File: packages/blade/src/components/Input/BaseInput/BaseInputWrapper.tsx (hunk 1 above)
Comment (harshsinghatz) [reply packages/blade/src/components/Input/BaseInput/BaseInputWrapper.tsx:78]: yes, this is because of change in component composition

**Comment by harshsinghatz** [comment]
@saurabhdaware I somehow missed this notification, plz review

**Review by saurabhdaware — DISMISSED** [review]
Looks good to me 🥳

**Comment by saurabhdaware** [comment]
@harshsinghatz  Can you update the snapshots? `yarn react:test -u` and `yarn react-native:test -u` should do it I guess.

**Comment by harshsinghatz** [comment]
> @harshsinghatz  Can you update the snapshots? `yarn react:test -u` and `yarn react-native:test -u` should do it I guess.

Done

**Comment by anuraghazra** [comment]
@harshsinghatz i think there are few conflicts, can you pull the master changes and run the snapshots again?

**Comment by harshsinghatz** [comment]
@anuraghazra 
image

Locally 3 test cases are failing for src/components/BottomSheet/__tests__/BottomSheet.web.test.tsx (even on latest master pull)

**Comment by anuraghazra** [comment]
> Locally 3 test cases are failing for src/components/BottomSheet/tests/BottomSheet.web.test.tsx

Yea those tests are a bit flaky will see whats the issue.

**Comment by anuraghazra** [comment]
@harshsinghatz Sorry to give you more trouble but seems like there is another bug with the helpText. 

Right now the helpText & the maxChar limiter text is shifted a bit downwards: 
image


It should be like this: 
image

File: packages/blade/src/components/Input/BaseInput/BaseInputWrapper.tsx (hunk 1 above)
Comment (anuraghazra) [inline packages/blade/src/components/Input/BaseInput/BaseInputWrapper.tsx:78]: Since we removed this `isLabelLeftPositioned` can you remove the types and other remnants?

Comment (harshsinghatz) [reply packages/blade/src/components/Input/BaseInput/BaseInputWrapper.tsx:78]: removed

**Comment by harshsinghatz** [comment]
> @harshsinghatz Sorry to give you more trouble but seems like there is another bug with the helpText.
> 
> Right now the helpText & the maxChar limiter text is shifted a bit downwards: image
> 
> It should be like this: image

Hmm, this would require moving the formhint inside the BaseInputWrapper, not sure if this would be a good decision as this would adding unnecessary APIs for BaseInputWrapper. 

Not sure if there is any other way around this!

**Comment by anuraghazra** [comment]
@harshsinghatz okay let's do this separately, I've opened up a new issue to track this bug. 
https://github.com/razorpay/blade/issues/1271

Let's close this PR first.

**Comment by anuraghazra** [comment]
@harshsinghatz can you resolve conflict & update the snapshots

**Review by saurabhdaware — APPROVED** [review]

**Comment by kamleshchandnani** [comment]
fixes: #1271
